services:
  db:
    image: bitnami/mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'

    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - mysql-data:/bitnami/mysql 

volumes:
  mysql-data: