import { v4 as uuidv4 } from 'uuid'

export const ProductsList = [
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }],
  //   name: 'Expresso Tradicional',
  //   description: 'O tradicional café feito com água quente e grãos moídos',
  //   price: 1,
  //   image: 'src/assets/coffee/Expresso.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }],
  //   name: 'Expresso Americano',
  //   description: 'Expresso diluído, menos intenso que o tradicional',
  //   price: 1,
  //   image: 'src/assets/coffee/Americano.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }],
  //   name: 'Expresso Cremoso',
  //   description: 'Café expresso tradicional com espuma cremosa',
  //   price: 1,
  //   image: 'src/assets/coffee/Expresso Cremoso.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Gelado' }],
  //   name: 'Expresso Gelado',
  //   description: 'Bebida preparada com café expresso e cubos de gelo',
  //   price: 1,
  //   image: 'src/assets/coffee/Café Gelado.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Com leite' }],
  //   name: 'Café com Leite',
  //   description: 'Meio a meio de expresso tradicional com leite vaporizado',
  //   price: 1,
  //   image: 'src/assets/coffee/Café com Leite.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Com leite' }],
  //   name: 'Latte',
  //   description:
  //     'Uma dose de café expresso com o dobro de leite e espuma cremosa',
  //   price: 1,
  //   image: 'src/assets/coffee/Latte.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Com leite' }],
  //   name: 'Capuccino',
  //   description:
  //     'Bebida com canela feita de doses iguais de café, leite e espuma',
  //   price: 1,
  //   image: 'src/assets/coffee/Capuccino.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Com leite' }],
  //   name: 'Macchiato',
  //   description:
  //     'Café expresso misturado com um pouco de leite quente e espuma',
  //   price: 1,
  //   image: 'src/assets/coffee/Macchiato.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Tradicional' }, { title: 'Com leite' }],
  //   name: 'Mocaccino',
  //   description: 'Café expresso com calda de chocolate, pouco leite e espuma',
  //   price: 1,
  //   image: 'src/assets/coffee/Mochaccino.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Especial' }, { title: 'Com leite' }],
  //   name: 'Chocolate Quente',
  //   description: 'Bebida feita com chocolate dissolvido no leite quente e café',
  //   price: 1,
  //   image: 'src/assets/coffee/Chocolate Quente.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Especial' }],
  //   name: 'Havaiano',
  //   description: 'Bebida adocicada preparada com café e leite de coco',
  //   price: 1,
  //   image: 'src/assets/coffee/Havaiano.png',
  //   count: 0,
  // },
  // {
  //   id: uuidv4(),
  //   tag: [{ title: 'Especial' }],
  //   name: 'Árabe',
  //   description: 'Bebida preparada com grãos de café árabe e especiarias',
  //   price: 1,
  //   image: 'src/assets/coffee/Árabe.png',
  //   count: 0,
  // },
  {
    id: uuidv4(),
    tag: [{ title: 'Especial' }, { title: 'Alcoólico' }],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 1,
    image: 'src/assets/coffee/Irlandês.png',
    count: 1,
  },
  {
    id: uuidv4(),
    tag: [{ title: 'Especial' }, { title: 'Alcoólico' }, { title: 'Gelado' }],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 1,
    image: 'src/assets/coffee/Cubano.png',
    count: 1,
  },
]
